init commit
iddanilov/gopher-market pull request #1
Opened 2022-09-30 16:20 UTC by iddanilov

2022-12-01 10:06 UTC, rktkov requested changes
1. В файл readme - надо добавить схему с общей архитектурой решения.
2. В файле readme  - надо словами расписать процедуру / процедуры взаимодействия между разрабатываемым сервисом и внешним сервисом. В идеале нарисовать - sequence diagram
3. В файле readme - расписать логику работы с балансом пользователя, когда и как он изменяется.
4. В файле readme -  показать ER  диаграмму сущностей БД.

2022-12-08 09:08 UTC, rktkov requested changes

2022-12-16 05:12 UTC, iddanilov commented on internal/service/orders.go
> +func (s *OrderService) writeInfoAboutOrder(userID int, orderID string) {
Вынес в отдельный сервис

2022-12-21 10:41 UTC, rktkov requested changes

2022-12-21 10:41 UTC, rktkov commented on internal/service/loyalty.go
> +				log.Println("ERROR can't save accrual: ", err)
А вот тут не получается ли ситуация, что мы потеряли запрос, если возникла ошибка. Ведь мы данные из канала считали и их там больше нет.

2022-12-21 10:41 UTC, rktkov commented on internal/service/loyalty.go
> +			if err != nil {
А что за ошибку мы проверяем тут? выше мы уже обработали последнюю полученную в строчке 35, это дублирование проверки.

2022-12-21 10:41 UTC, rktkov commented on internal/service/loyalty.go
> +			go func(userID string, accrual float32) {
Мне не нравиться, что мы запускаем 2 параллельных изменения в репозитории независимо друг от друга. Если хотя бы в одной из операции произойдет ошибка мы столкнемся с ситуацией, когда данные в репозитории не согласованы.

2022-12-21 10:41 UTC, rktkov commented on internal/service/loyalty.go
> +	loyaltyCh chan models.LoyaltyChan
Так как мы из канала только читаем, то его объявление можно сделать более строгим, явно указав направление работы.

2022-12-25 09:49 UTC, iddanilov commented on internal/service/loyalty.go
> +			if err != nil {
Убрал!

2022-12-25 15:35 UTC, iddanilov commented on internal/service/loyalty.go
> +			go func(userID string, accrual float32) {
Да, согласен! Поправил!

2022-12-25 15:51 UTC, iddanilov commented on internal/service/loyalty.go
> +				log.Println("ERROR can't save accrual: ", err)
Поправил. Убрал возвращение ошибки. Я хотел использовать Kafka для этих целей, но как я понимаю в учебном окружение нет Kafka...

2023-01-11 16:12 UTC, rktkov approved these changes

2023-06-22 15:02 UTC, merged